import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  background: {
    flex: 1,
    backgroundColor: '#fafafa',
  },
  container: {
    padding: 0,
    backgroundColor: '#fff',
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    paddingBottom: 120,
    minHeight: '100%',
  },
  labelMain: {
    fontSize: 16,
    color: '#222',
    fontWeight: '500',
    marginTop: 16,
    marginBottom: 18,
    marginLeft: 16,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 18,
    marginLeft: 16,
    marginRight: 16,
  },
  label: {
    width: 60,
    color: '#b0b0b0',
    fontSize: 15,
    fontWeight: '400',
  },
  input: {
    flex: 1,
    borderBottomWidth: 1,
    borderColor: '#e0e0e0',
    fontSize: 15,
    paddingVertical: 8,
    paddingHorizontal: 0,
    color: '#222',
    backgroundColor: 'transparent',
    marginLeft: 12,
  },
  inputRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 12,
  },
  dropdown: {
    marginLeft: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 4,
    backgroundColor: '#f5f5f5',
  },
  dropdownText: {
    fontSize: 15,
    color: '#888',
  },
  imageBox: {
    flex: 1,
    height: 90,
    borderWidth: 1,
    borderColor: '#d7e7d7',
    borderStyle: 'dashed',
    borderRadius: 8,
    backgroundColor: '#f8fcf8',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 12,
  },
  imageIcon: {
    width: 40,
    height: 40,
    opacity: 0.3,
  },
  personalityWrap: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginLeft: 12,
  },
  personalityBtn: {
    borderWidth: 1,
    borderColor: '#5CD79E',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 4,
    marginRight: 4,
    marginBottom: 4,
    backgroundColor: '#fff',
  },
  personalityBtnSelected: {
    backgroundColor: '#99DDAA',
    borderColor: '#99DDAA',
  },
  personalityText: {
    color: '#5CD79E',
    fontWeight: '500',
    fontSize: 15,
  },
  personalityTextSelected: {
    color: '#fff',
    fontWeight: '700',
  },
  inputUnderPersonality: {
    marginTop: 4,
    marginLeft: 0,
  },
});
