import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#f5f4f1',
  },
  keyboardWrap: {
    flex: 1,
  },
  body: {
    flex: 1,
    backgroundColor: '#fff',
  },
  dateWrap: {
    alignSelf: 'center',
    marginTop: 15,
    marginBottom: 10,
    paddingHorizontal: 18,
    paddingVertical: 6,
    borderRadius: 15,
    backgroundColor: '#efefef',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 4,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    elevation: 1,
  },
  dateText: {
    fontSize: 12,
    color: '#4b4b4b',
    fontWeight: '500',
  },
  messageList: {
    paddingHorizontal: 18,
    paddingTop: 4,
    paddingBottom: 72,
    flexGrow: 1,
  },
  messageListViewport: {
    flex: 1,
  },
  messageListLifted: {
    paddingBottom: 72,
  },
  messageRow: {
    marginBottom: 14,
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  messageRowMe: {
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
  },
  messageRowOther: {
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  messageColumn: {
    maxWidth: '72%',
  },
  messageColumnMe: {
    alignItems: 'flex-end',
    marginLeft: 'auto',
  },
  messageColumnOther: {
    alignItems: 'flex-start',
  },
avatar: {
  width: 40,
  height: 40,
  borderRadius: 20,
  borderWidth: 1,
  borderColor: '#d6e8d9',
  backgroundColor: '#eef7ef',
  marginRight: 4,
  overflow: 'hidden',
},
avatarImage: {
  width: '100%',
  height: '100%',
  resizeMode: 'contain',
},
  messageBubble: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 15,
    borderWidth: 1,
  },
  messageBubbleMe: {
    backgroundColor: '#d9f4df',
    borderColor: '#c6e6cd',
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 4,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    elevation: 1,
  },
  messageBubbleOther: {
    backgroundColor: '#fff',
    borderColor: '#e6e6e6',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 4,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    elevation: 1,
  },
  messageText: {
    fontSize: 15,
    color: '#1f1f1f',
  },
  messageTextMe: {
    color: '#1b1b1b',
  },
  messageTextOther: {
    color: '#1f1f1f',
  },
  messageTime: {
    fontSize: 12,
    color: '#b0b0b0',
    marginTop: 4,
  },
  messageTimeMe: {
    marginRight: 4,
  },
  messageTimeOther: {
    marginLeft: 4,
  },
  quickReplyWrap: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 10,
    flexWrap: 'wrap',
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  quickReplyButton: {
    borderWidth: 1,
    borderColor: '#79d791',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#fff',
  },
  quickReplyText: {
    fontSize: 13,
    color: '#1d1d1d',
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 10,
    paddingHorizontal: 16,
    paddingBottom: 14,
    paddingTop: 6,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  input: {
    flex: 1,
    minHeight: 52,
    borderWidth: 1,
    borderColor: '#d9d9d9',
    borderRadius: 4,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: '#1f1f1f',
    backgroundColor: '#fff',
  },
  sendButton: {
    width: 52,
    height: 52,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#d9d9d9',
    marginBottom: 0,
  },
  sendIcon: {
    fontSize: 18,
    color: '#cfd0d6',
    fontWeight: '700',
  },
  scrollToBottomButton: {
    position: 'absolute',
    left: '50%',
    bottom: 133,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#d9e3dc',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 6,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    elevation: 3,
    transform: [{ translateX: -20 }],
  },
  scrollToBottomIcon: {
    fontSize: 18,
    lineHeight: 20,
    color: '#6f7c75',
    fontWeight: '700',
  },
});
