import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 20,
        paddingTop: 14,
    },

    countBadge: {
        fontSize: 12,
        fontWeight: '600',
        color: '#7FC77C',
        backgroundColor: '#E8F7EF',
        alignSelf: 'flex-start',
        paddingVertical: 4,
        paddingHorizontal: 10,
        borderRadius: 20,
        marginBottom: 12,
    },
    listFlex: { flex: 1 },
    listContent: { paddingBottom: 100 },

    entryRow: {
        flexDirection: 'row',
        gap: 10,
        paddingVertical: 8,
    },
    dotCol: {
        alignItems: 'center',
        paddingTop: 4,
    },
    dot: {
        width: 9,
        height: 9,
        borderRadius: 5,
        backgroundColor: '#7FC77C',
    },
    dotLine: {
        width: 1.5,
        flex: 1,
        minHeight: 40,
        backgroundColor: '#C8E6C9',
        marginTop: 3,
    },
    entryContent: { flex: 1 },
    entryDate: {
        fontSize: 11,
        fontWeight: '500',
        color: '#9CA3AF',
        marginBottom: 4,
    },
    entryImage: {
        width: '100%',
        height: 100,
        borderRadius: 12,
        backgroundColor: '#E5E7EB',
        marginBottom: 6,
    },
    entryImagePlaceholder: { width: '100%', height: 6 },
    entryNoteRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 6,
    },
    entryMoodEmoji: { fontSize: 14, marginTop: 1 },
    entryNote: {
        flex: 1,
        fontSize: 13,
        color: '#6B7280',
        lineHeight: 19,
    },

    emptyWrap: { alignItems: 'center', paddingVertical: 60 },
    emptyEmoji: { fontSize: 32, marginBottom: 10 },
    emptyText: {
        fontSize: 13,
        color: '#9CA3AF',
        textAlign: 'center',
        lineHeight: 20,
    },

    writeButton: {
        position: 'absolute',
        bottom: 20,
        right: 20,
        width: 52,
        height: 52,
        borderRadius: 26,
        backgroundColor: '#7FC77C',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 6,
        elevation: 4,
    },

    detailContent: { paddingBottom: 40 },
    detailMetaRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 12,
    },
    detailDate: {
        fontSize: 16,
        fontWeight: '700',
        color: '#1F2937',
    },
    dayBadge: {
        backgroundColor: '#E8F7EF',
        paddingVertical: 3,
        paddingHorizontal: 8,
        borderRadius: 20,
    },
    dayBadgeText: {
        fontSize: 11,
        fontWeight: '700',
        color: '#7FC77C',
    },
    detailPhotoScroll: { marginBottom: 12 },
    detailPhoto: {
        width: 220,
        height: 220,
        borderRadius: 16,
        backgroundColor: '#E5E7EB',
        marginRight: 10,
    },
    moodRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: '#F8FAFC',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 10,
        paddingVertical: 8,
        paddingHorizontal: 10,
        marginBottom: 12,
    },
    moodEmoji: { fontSize: 16 },
    moodLabel: {
        fontSize: 12,
        fontWeight: '600',
        color: '#6B7280',
    },
    detailNote: {
        fontSize: 14,
        color: '#1F2937',
        lineHeight: 22,
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 12,
        padding: 12,
        marginBottom: 16,
    },

    sensorTitle: {
        fontSize: 11,
        fontWeight: '600',
        color: '#9CA3AF',
        marginBottom: 6,
    },
    sensorRow: { flexDirection: 'row', gap: 8, marginBottom: 18 },
    sensorChip: {
        flex: 1,
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 10,
        paddingVertical: 10,
        alignItems: 'center',
    },
    sensorValue: {
        fontSize: 14,
        fontWeight: '700',
        color: '#1F2937',
    },
    sensorLabel: {
        fontSize: 10,
        color: '#9CA3AF',
        marginTop: 2,
    },

    detailActionRow: { flexDirection: 'row', gap: 10 },
    detailActionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingVertical: 14,
        borderRadius: 14,
        backgroundColor: '#7FC77C',
    },
    detailActionButtonHalf: { flex: 1 },
    detailActionText: {
        fontSize: 14,
        fontWeight: '700',
        color: '#FFFFFF',
    },

    formContent: { paddingBottom: 40 },

    formLabell: {
        fontSize: 15,
        fontWeight: '500',
        color: '#9CA3AF',
        marginBottom: 6,
    },
    formLabel: {
        fontSize: 15,
        fontWeight: '500',
        color: '#9CA3AF',
        marginTop: 14,
        marginBottom: 6,
    },
    formLabelOpt: {
        fontSize: 12,
        fontWeight: '400',
        color: '#9CA3AF',
    },

    photoRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
    photoThumbWrap: { position: 'relative' },
    photoThumb: {
        width: 150,
        height: 150,
        borderRadius: 12,
        backgroundColor: '#E5E7EB',
    },
    photoRemoveBtn: {
        position: 'absolute',
        top: -6,
        right: -6,
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: '#00000099',
        alignItems: 'center',
        justifyContent: 'center',
    },
    photoAddBox: {
        width: '100%',
        height: 120,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderStyle: 'dashed',
        backgroundColor: '#E5E7EB',
        alignItems: 'center',
        justifyContent: 'center',
    },
    photoAddBoxText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#9CA3AF',
        marginTop: 4,
    },

    moodPickRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
    moodChip: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 3,
        paddingVertical: 5,
        paddingHorizontal: 12,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#7FC77C',
        backgroundColor: '#FFFFFF',
    },
    moodChipActive: {
        backgroundColor: '#7FC77C',
        borderColor: '#7FC77C',
    },
    moodChipEmoji: { fontSize: 14 },
    moodChipText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#7FC77C',
    },
    moodChipTextActive: { color: '#FFFFFF', fontWeight: '700' },

    noteInput: {
        minHeight: 120,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 10,
        padding: 12,
        fontSize: 14,
        color: '#1F2937',
        lineHeight: 21,
    },
    noteCount: {
        alignSelf: 'flex-end',
        fontSize: 12,
        color: '#9CA3AF',
        marginTop: 4,
    },

    sensorInfoCard: {
        flexDirection: 'row',
        backgroundColor: '#F7FBF7',
        borderWidth: 1,
        borderColor: '#DCEFDC',
        borderRadius: 12,
        padding: 12,
        marginTop: 16,
    },
    sensorInfoText: {
        fontSize: 12,
        color: '#5A8A5A',
        lineHeight: 18,
    },

    submitButton: {
        marginTop: 22,
        backgroundColor: '#7FC77C',
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
    },
    submitButtonDisabled: { backgroundColor: '#E5E7EB' },
    submitButtonText: {
        fontSize: 16,
        fontWeight: '700',
        color: '#FFFFFF',
    },

    emptyText: {
        textAlign: 'center',
        color: '#9CA3AF',
        fontSize: 14,
        marginTop: 40,
    },
});