import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F5F8F5' },
  content: { padding: 18, paddingBottom: 40, gap: 14 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  card: { backgroundColor: '#FFFFFF', borderRadius: 20, padding: 18 },
  statusCard: { backgroundColor: '#EAF7ED', borderRadius: 20, padding: 18 },
  cardTitle: { fontSize: 17, fontWeight: '800', color: '#263C2D', marginBottom: 14 },
  statusRow: { flexDirection: 'row', gap: 12 },
  statusItem: { flex: 1, backgroundColor: 'rgba(255,255,255,0.8)', borderRadius: 14, padding: 14 },
  statusLabel: { color: '#718078', fontSize: 12, fontWeight: '600' },
  statusValue: { marginTop: 6, color: '#315D3A', fontSize: 18, fontWeight: '800' },
  caption: { marginTop: 5, color: '#829087', fontSize: 12 },
  field: { marginTop: 10 },
  fieldLabel: { marginBottom: 7, color: '#53625A', fontSize: 13, fontWeight: '700' },
  input: { height: 46, borderRadius: 13, borderWidth: 1, borderColor: '#DCE7DE', paddingHorizontal: 14, color: '#24362A', backgroundColor: '#FAFCFA' },
  primaryButton: { height: 50, marginTop: 14, borderRadius: 25, alignItems: 'center', justifyContent: 'center', backgroundColor: '#68B578' },
  primaryButtonText: { color: '#FFFFFF', fontSize: 15, fontWeight: '800' },
  secondaryButton: { height: 48, marginTop: 16, borderRadius: 24, alignItems: 'center', justifyContent: 'center', borderWidth: 1.5, borderColor: '#68B578' },
  secondaryButtonText: { color: '#4A9B5B', fontSize: 15, fontWeight: '800' },
  modeRow: { flexDirection: 'row', gap: 7 },
  modeButton: { flex: 1, paddingVertical: 10, alignItems: 'center', borderRadius: 12, backgroundColor: '#F0F3F1' },
  modeButtonActive: { backgroundColor: '#DDF1E1' },
  modeText: { color: '#7A8580', fontSize: 12, fontWeight: '700' },
  modeTextActive: { color: '#3D8D50' },
  switchRow: { marginTop: 15, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  switchTitle: { color: '#34483B', fontSize: 14, fontWeight: '800' },
  warning: { marginTop: 12, color: '#A36A28', fontSize: 12, lineHeight: 18 },
  emptyText: { color: '#8B9690', fontSize: 13 },
  historyRow: { paddingVertical: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#E4EBE6', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  historyAmount: { color: '#34483B', fontSize: 14, fontWeight: '700' },
  historyStatus: { color: '#4A9B5B', fontSize: 13, fontWeight: '800' },
});
